// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using Elastic.Clients.Elasticsearch.Fluent;
using Elastic.Clients.Elasticsearch.Next;
using Elastic.Clients.Elasticsearch.Serialization;
using Elastic.Transport.Products.Elasticsearch;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Elastic.Clients.Elasticsearch.QueryRules;

internal sealed partial class GetRuleResponseConverter : System.Text.Json.Serialization.JsonConverter<GetRuleResponse>
{
	private static readonly System.Text.Json.JsonEncodedText PropActions = System.Text.Json.JsonEncodedText.Encode("actions");
	private static readonly System.Text.Json.JsonEncodedText PropCriteria = System.Text.Json.JsonEncodedText.Encode("criteria");
	private static readonly System.Text.Json.JsonEncodedText PropPriority = System.Text.Json.JsonEncodedText.Encode("priority");
	private static readonly System.Text.Json.JsonEncodedText PropRuleId = System.Text.Json.JsonEncodedText.Encode("rule_id");
	private static readonly System.Text.Json.JsonEncodedText PropType = System.Text.Json.JsonEncodedText.Encode("type");

	public override GetRuleResponse Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
	{
		reader.ValidateToken(System.Text.Json.JsonTokenType.StartObject);
		LocalJsonProperty<Elastic.Clients.Elasticsearch.QueryRules.QueryRuleActions> propActions = default;
		LocalJsonProperty<IReadOnlyCollection<Elastic.Clients.Elasticsearch.QueryRules.QueryRuleCriteria>> propCriteria = default;
		LocalJsonProperty<int?> propPriority = default;
		LocalJsonProperty<string> propRuleId = default;
		LocalJsonProperty<Elastic.Clients.Elasticsearch.QueryRules.QueryRuleType> propType = default;
		while (reader.Read() && reader.TokenType is System.Text.Json.JsonTokenType.PropertyName)
		{
			if (propActions.TryRead(ref reader, options, PropActions))
			{
				continue;
			}

			if (propCriteria.TryRead(ref reader, options, PropCriteria, typeof(SingleOrManyMarker<IReadOnlyCollection<Elastic.Clients.Elasticsearch.QueryRules.QueryRuleCriteria>, Elastic.Clients.Elasticsearch.QueryRules.QueryRuleCriteria>)))
			{
				continue;
			}

			if (propPriority.TryRead(ref reader, options, PropPriority))
			{
				continue;
			}

			if (propRuleId.TryRead(ref reader, options, PropRuleId))
			{
				continue;
			}

			if (propType.TryRead(ref reader, options, PropType))
			{
				continue;
			}

			throw new System.Text.Json.JsonException($"Unknown JSON property '{reader.GetString()}' for type '{typeToConvert.Name}'.");
		}

		reader.ValidateToken(System.Text.Json.JsonTokenType.EndObject);
		return new GetRuleResponse
		{
			Actions = propActions.Value
,
			Criteria = propCriteria.Value
,
			Priority = propPriority.Value
,
			RuleId = propRuleId.Value
,
			Type = propType.Value
		};
	}

	public override void Write(System.Text.Json.Utf8JsonWriter writer, GetRuleResponse value, System.Text.Json.JsonSerializerOptions options)
	{
		writer.WriteStartObject();
		writer.WriteProperty(options, PropActions, value.Actions);
		writer.WriteProperty(options, PropCriteria, value.Criteria, typeof(SingleOrManyMarker<IReadOnlyCollection<Elastic.Clients.Elasticsearch.QueryRules.QueryRuleCriteria>, Elastic.Clients.Elasticsearch.QueryRules.QueryRuleCriteria>));
		writer.WriteProperty(options, PropPriority, value.Priority);
		writer.WriteProperty(options, PropRuleId, value.RuleId);
		writer.WriteProperty(options, PropType, value.Type);
		writer.WriteEndObject();
	}
}

[JsonConverter(typeof(GetRuleResponseConverter))]
public sealed partial class GetRuleResponse : ElasticsearchResponse
{
	/// <summary>
	/// <para>
	/// The actions to take when the rule is matched.
	/// The format of this action depends on the rule type.
	/// </para>
	/// </summary>
	public Elastic.Clients.Elasticsearch.QueryRules.QueryRuleActions Actions { get; init; }

	/// <summary>
	/// <para>
	/// The criteria that must be met for the rule to be applied.
	/// If multiple criteria are specified for a rule, all criteria must be met for the rule to be applied.
	/// </para>
	/// </summary>
	public IReadOnlyCollection<Elastic.Clients.Elasticsearch.QueryRules.QueryRuleCriteria> Criteria { get; init; }
	public int? Priority { get; init; }

	/// <summary>
	/// <para>
	/// A unique identifier for the rule.
	/// </para>
	/// </summary>
	public string RuleId { get; init; }

	/// <summary>
	/// <para>
	/// The type of rule.
	/// <c>pinned</c> will identify and pin specific documents to the top of search results.
	/// <c>exclude</c> will exclude specific documents from search results.
	/// </para>
	/// </summary>
	public Elastic.Clients.Elasticsearch.QueryRules.QueryRuleType Type { get; init; }
}