// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using Elastic.Clients.Elasticsearch.Fluent;
using Elastic.Clients.Elasticsearch.Next;
using Elastic.Clients.Elasticsearch.Serialization;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq.Expressions;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Elastic.Clients.Elasticsearch;

/// <summary>
/// <para><see href="https://www.elastic.co/guide/en/elasticsearch/reference/8.17/sort-search-results.html">Learn more about this API in the Elasticsearch documentation.</see></para>
/// </summary>
[JsonConverter(typeof(SortOptionsConverter))]
public sealed partial class SortOptions
{
	internal SortOptions(string variantName, object variant)
	{
		if (variantName is null)
			throw new ArgumentNullException(nameof(variantName));
		if (variant is null)
			throw new ArgumentNullException(nameof(variant));
		if (string.IsNullOrWhiteSpace(variantName))
			throw new ArgumentException("Variant name must not be empty or whitespace.");
		VariantType = variantName;
		Variant = variant;
	}

	internal SortOptions()
	{
	}

	public object Variant { get; internal set; }
	public string VariantType { get; internal set; }

	public static SortOptions Doc(Elastic.Clients.Elasticsearch.ScoreSort scoreSort) => new SortOptions("_doc", scoreSort);
	public static SortOptions GeoDistance(Elastic.Clients.Elasticsearch.GeoDistanceSort geoDistanceSort) => new SortOptions("_geo_distance", geoDistanceSort);
	public static SortOptions Score(Elastic.Clients.Elasticsearch.ScoreSort scoreSort) => new SortOptions("_score", scoreSort);
	public static SortOptions Script(Elastic.Clients.Elasticsearch.ScriptSort scriptSort) => new SortOptions("_script", scriptSort);

	public bool TryGet<T>([NotNullWhen(true)] out T? result) where T : class
	{
		result = default;
		if (Variant is T variant)
		{
			result = variant;
			return true;
		}

		return false;
	}
}

internal sealed partial class SortOptionsConverter : System.Text.Json.Serialization.JsonConverter<SortOptions>
{
	private static readonly System.Text.Json.JsonEncodedText VariantDoc = System.Text.Json.JsonEncodedText.Encode("_doc");
	private static readonly System.Text.Json.JsonEncodedText VariantGeoDistance = System.Text.Json.JsonEncodedText.Encode("_geo_distance");
	private static readonly System.Text.Json.JsonEncodedText VariantScore = System.Text.Json.JsonEncodedText.Encode("_score");
	private static readonly System.Text.Json.JsonEncodedText VariantScript = System.Text.Json.JsonEncodedText.Encode("_script");

	public override SortOptions Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
	{
		reader.ValidateToken(System.Text.Json.JsonTokenType.StartObject);
		var variantType = string.Empty;
		object? variant = null;
		while (reader.Read() && reader.TokenType is System.Text.Json.JsonTokenType.PropertyName)
		{
			if (reader.ValueTextEquals(VariantDoc))
			{
				variantType = VariantDoc.Value;
				variant = reader.ReadValue<Elastic.Clients.Elasticsearch.ScoreSort?>(options);
				continue;
			}

			if (reader.ValueTextEquals(VariantGeoDistance))
			{
				variantType = VariantGeoDistance.Value;
				variant = reader.ReadValue<Elastic.Clients.Elasticsearch.GeoDistanceSort?>(options);
				continue;
			}

			if (reader.ValueTextEquals(VariantScore))
			{
				variantType = VariantScore.Value;
				variant = reader.ReadValue<Elastic.Clients.Elasticsearch.ScoreSort?>(options);
				continue;
			}

			if (reader.ValueTextEquals(VariantScript))
			{
				variantType = VariantScript.Value;
				variant = reader.ReadValue<Elastic.Clients.Elasticsearch.ScriptSort?>(options);
				continue;
			}

			throw new System.Text.Json.JsonException($"Unknown JSON property '{reader.GetString()}' for type '{typeToConvert.Name}'.");
		}

		reader.ValidateToken(System.Text.Json.JsonTokenType.EndObject);
		return new SortOptions { VariantType = variantType, Variant = variant };
	}

	public override void Write(System.Text.Json.Utf8JsonWriter writer, SortOptions value, System.Text.Json.JsonSerializerOptions options)
	{
		writer.WriteStartObject();
		switch (value.VariantType)
		{
			case "":
				break;
			case "_doc":
				writer.WriteProperty(options, value.VariantType, (Elastic.Clients.Elasticsearch.ScoreSort?)value.Variant);
				break;
			case "_geo_distance":
				writer.WriteProperty(options, value.VariantType, (Elastic.Clients.Elasticsearch.GeoDistanceSort?)value.Variant);
				break;
			case "_score":
				writer.WriteProperty(options, value.VariantType, (Elastic.Clients.Elasticsearch.ScoreSort?)value.Variant);
				break;
			case "_script":
				writer.WriteProperty(options, value.VariantType, (Elastic.Clients.Elasticsearch.ScriptSort?)value.Variant);
				break;
			default:
				throw new System.Text.Json.JsonException($"Variant '{value.VariantType}' is not supported for type '{nameof(SortOptions)}'.");
		}

		writer.WriteEndObject();
	}
}

public sealed partial class SortOptionsDescriptor<TDocument> : SerializableDescriptor<SortOptionsDescriptor<TDocument>>
{
	internal SortOptionsDescriptor(Action<SortOptionsDescriptor<TDocument>> configure) => configure.Invoke(this);

	public SortOptionsDescriptor() : base()
	{
	}

	private bool ContainsVariant { get; set; }
	private string ContainedVariantName { get; set; }
	private object Variant { get; set; }
	private Descriptor Descriptor { get; set; }

	private SortOptionsDescriptor<TDocument> Set<T>(Action<T> descriptorAction, string variantName) where T : Descriptor
	{
		ContainedVariantName = variantName;
		ContainsVariant = true;
		var descriptor = (T)Activator.CreateInstance(typeof(T), true);
		descriptorAction?.Invoke(descriptor);
		Descriptor = descriptor;
		return Self;
	}

	private SortOptionsDescriptor<TDocument> Set(object variant, string variantName)
	{
		Variant = variant;
		ContainedVariantName = variantName;
		ContainsVariant = true;
		return Self;
	}

	public SortOptionsDescriptor<TDocument> Doc(Elastic.Clients.Elasticsearch.ScoreSort scoreSort) => Set(scoreSort, "_doc");
	public SortOptionsDescriptor<TDocument> Doc(Action<Elastic.Clients.Elasticsearch.ScoreSortDescriptor> configure) => Set(configure, "_doc");
	public SortOptionsDescriptor<TDocument> GeoDistance(Elastic.Clients.Elasticsearch.GeoDistanceSort geoDistanceSort) => Set(geoDistanceSort, "_geo_distance");
	public SortOptionsDescriptor<TDocument> GeoDistance(Action<Elastic.Clients.Elasticsearch.GeoDistanceSortDescriptor<TDocument>> configure) => Set(configure, "_geo_distance");
	public SortOptionsDescriptor<TDocument> Score(Elastic.Clients.Elasticsearch.ScoreSort scoreSort) => Set(scoreSort, "_score");
	public SortOptionsDescriptor<TDocument> Score(Action<Elastic.Clients.Elasticsearch.ScoreSortDescriptor> configure) => Set(configure, "_score");
	public SortOptionsDescriptor<TDocument> Script(Elastic.Clients.Elasticsearch.ScriptSort scriptSort) => Set(scriptSort, "_script");
	public SortOptionsDescriptor<TDocument> Script(Action<Elastic.Clients.Elasticsearch.ScriptSortDescriptor<TDocument>> configure) => Set(configure, "_script");

	protected override void Serialize(Utf8JsonWriter writer, JsonSerializerOptions options, IElasticsearchClientSettings settings)
	{
		writer.WriteStartObject();
		if (!string.IsNullOrEmpty(ContainedVariantName))
		{
			writer.WritePropertyName(ContainedVariantName);
			if (Variant is not null)
			{
				JsonSerializer.Serialize(writer, Variant, Variant.GetType(), options);
				writer.WriteEndObject();
				return;
			}

			JsonSerializer.Serialize(writer, Descriptor, Descriptor.GetType(), options);
		}

		writer.WriteEndObject();
	}
}

public sealed partial class SortOptionsDescriptor : SerializableDescriptor<SortOptionsDescriptor>
{
	internal SortOptionsDescriptor(Action<SortOptionsDescriptor> configure) => configure.Invoke(this);

	public SortOptionsDescriptor() : base()
	{
	}

	private bool ContainsVariant { get; set; }
	private string ContainedVariantName { get; set; }
	private object Variant { get; set; }
	private Descriptor Descriptor { get; set; }

	private SortOptionsDescriptor Set<T>(Action<T> descriptorAction, string variantName) where T : Descriptor
	{
		ContainedVariantName = variantName;
		ContainsVariant = true;
		var descriptor = (T)Activator.CreateInstance(typeof(T), true);
		descriptorAction?.Invoke(descriptor);
		Descriptor = descriptor;
		return Self;
	}

	private SortOptionsDescriptor Set(object variant, string variantName)
	{
		Variant = variant;
		ContainedVariantName = variantName;
		ContainsVariant = true;
		return Self;
	}

	public SortOptionsDescriptor Doc(Elastic.Clients.Elasticsearch.ScoreSort scoreSort) => Set(scoreSort, "_doc");
	public SortOptionsDescriptor Doc(Action<Elastic.Clients.Elasticsearch.ScoreSortDescriptor> configure) => Set(configure, "_doc");
	public SortOptionsDescriptor GeoDistance(Elastic.Clients.Elasticsearch.GeoDistanceSort geoDistanceSort) => Set(geoDistanceSort, "_geo_distance");
	public SortOptionsDescriptor GeoDistance<TDocument>(Action<Elastic.Clients.Elasticsearch.GeoDistanceSortDescriptor> configure) => Set(configure, "_geo_distance");
	public SortOptionsDescriptor Score(Elastic.Clients.Elasticsearch.ScoreSort scoreSort) => Set(scoreSort, "_score");
	public SortOptionsDescriptor Score(Action<Elastic.Clients.Elasticsearch.ScoreSortDescriptor> configure) => Set(configure, "_score");
	public SortOptionsDescriptor Script(Elastic.Clients.Elasticsearch.ScriptSort scriptSort) => Set(scriptSort, "_script");
	public SortOptionsDescriptor Script<TDocument>(Action<Elastic.Clients.Elasticsearch.ScriptSortDescriptor> configure) => Set(configure, "_script");

	protected override void Serialize(Utf8JsonWriter writer, JsonSerializerOptions options, IElasticsearchClientSettings settings)
	{
		writer.WriteStartObject();
		if (!string.IsNullOrEmpty(ContainedVariantName))
		{
			writer.WritePropertyName(ContainedVariantName);
			if (Variant is not null)
			{
				JsonSerializer.Serialize(writer, Variant, Variant.GetType(), options);
				writer.WriteEndObject();
				return;
			}

			JsonSerializer.Serialize(writer, Descriptor, Descriptor.GetType(), options);
		}

		writer.WriteEndObject();
	}
}