// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using Elastic.Clients.Elasticsearch.Fluent;
using Elastic.Clients.Elasticsearch.Next;
using Elastic.Clients.Elasticsearch.Serialization;
using Elastic.Transport.Products.Elasticsearch;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Elastic.Clients.Elasticsearch.Snapshot;

internal sealed partial class GetSnapshotResponseConverter : System.Text.Json.Serialization.JsonConverter<GetSnapshotResponse>
{
	private static readonly System.Text.Json.JsonEncodedText PropNext = System.Text.Json.JsonEncodedText.Encode("next");
	private static readonly System.Text.Json.JsonEncodedText PropRemaining = System.Text.Json.JsonEncodedText.Encode("remaining");
	private static readonly System.Text.Json.JsonEncodedText PropResponses = System.Text.Json.JsonEncodedText.Encode("responses");
	private static readonly System.Text.Json.JsonEncodedText PropSnapshots = System.Text.Json.JsonEncodedText.Encode("snapshots");
	private static readonly System.Text.Json.JsonEncodedText PropTotal = System.Text.Json.JsonEncodedText.Encode("total");

	public override GetSnapshotResponse Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
	{
		reader.ValidateToken(System.Text.Json.JsonTokenType.StartObject);
		LocalJsonProperty<string?> propNext = default;
		LocalJsonProperty<int> propRemaining = default;
		LocalJsonProperty<IReadOnlyCollection<Elastic.Clients.Elasticsearch.Snapshot.SnapshotResponseItem>?> propResponses = default;
		LocalJsonProperty<IReadOnlyCollection<Elastic.Clients.Elasticsearch.Snapshot.SnapshotInfo>?> propSnapshots = default;
		LocalJsonProperty<int> propTotal = default;
		while (reader.Read() && reader.TokenType is System.Text.Json.JsonTokenType.PropertyName)
		{
			if (propNext.TryRead(ref reader, options, PropNext))
			{
				continue;
			}

			if (propRemaining.TryRead(ref reader, options, PropRemaining))
			{
				continue;
			}

			if (propResponses.TryRead(ref reader, options, PropResponses))
			{
				continue;
			}

			if (propSnapshots.TryRead(ref reader, options, PropSnapshots))
			{
				continue;
			}

			if (propTotal.TryRead(ref reader, options, PropTotal))
			{
				continue;
			}

			throw new System.Text.Json.JsonException($"Unknown JSON property '{reader.GetString()}' for type '{typeToConvert.Name}'.");
		}

		reader.ValidateToken(System.Text.Json.JsonTokenType.EndObject);
		return new GetSnapshotResponse
		{
			Next = propNext.Value
,
			Remaining = propRemaining.Value
,
			Responses = propResponses.Value
,
			Snapshots = propSnapshots.Value
,
			Total = propTotal.Value
		};
	}

	public override void Write(System.Text.Json.Utf8JsonWriter writer, GetSnapshotResponse value, System.Text.Json.JsonSerializerOptions options)
	{
		writer.WriteStartObject();
		writer.WriteProperty(options, PropNext, value.Next);
		writer.WriteProperty(options, PropRemaining, value.Remaining);
		writer.WriteProperty(options, PropResponses, value.Responses);
		writer.WriteProperty(options, PropSnapshots, value.Snapshots);
		writer.WriteProperty(options, PropTotal, value.Total);
		writer.WriteEndObject();
	}
}

[JsonConverter(typeof(GetSnapshotResponseConverter))]
public sealed partial class GetSnapshotResponse : ElasticsearchResponse
{
	/// <summary>
	/// <para>
	/// If the request contained a size limit and there might be more results, a <c>next</c> field will be added to the response.
	/// It can be used as the <c>after</c> query parameter to fetch additional results.
	/// </para>
	/// </summary>
	public string? Next { get; init; }

	/// <summary>
	/// <para>
	/// The number of remaining snapshots that were not returned due to size limits and that can be fetched by additional requests using the <c>next</c> field value.
	/// </para>
	/// </summary>
	public int Remaining { get; init; }
	public IReadOnlyCollection<Elastic.Clients.Elasticsearch.Snapshot.SnapshotResponseItem>? Responses { get; init; }
	public IReadOnlyCollection<Elastic.Clients.Elasticsearch.Snapshot.SnapshotInfo>? Snapshots { get; init; }

	/// <summary>
	/// <para>
	/// The total number of snapshots that match the request when ignoring the size limit or <c>after</c> query parameter.
	/// </para>
	/// </summary>
	public int Total { get; init; }
}