// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using Elastic.Clients.Elasticsearch.Fluent;
using Elastic.Clients.Elasticsearch.Next;
using Elastic.Clients.Elasticsearch.Requests;
using Elastic.Clients.Elasticsearch.Serialization;
using Elastic.Transport;
using Elastic.Transport.Extensions;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Elastic.Clients.Elasticsearch.IndexManagement;

public sealed partial class AnalyzeIndexRequestParameters : RequestParameters
{
}

internal sealed partial class AnalyzeIndexRequestConverter : System.Text.Json.Serialization.JsonConverter<AnalyzeIndexRequest>
{
	private static readonly System.Text.Json.JsonEncodedText PropAnalyzer = System.Text.Json.JsonEncodedText.Encode("analyzer");
	private static readonly System.Text.Json.JsonEncodedText PropAttributes = System.Text.Json.JsonEncodedText.Encode("attributes");
	private static readonly System.Text.Json.JsonEncodedText PropCharFilter = System.Text.Json.JsonEncodedText.Encode("char_filter");
	private static readonly System.Text.Json.JsonEncodedText PropExplain = System.Text.Json.JsonEncodedText.Encode("explain");
	private static readonly System.Text.Json.JsonEncodedText PropField = System.Text.Json.JsonEncodedText.Encode("field");
	private static readonly System.Text.Json.JsonEncodedText PropFilter = System.Text.Json.JsonEncodedText.Encode("filter");
	private static readonly System.Text.Json.JsonEncodedText PropNormalizer = System.Text.Json.JsonEncodedText.Encode("normalizer");
	private static readonly System.Text.Json.JsonEncodedText PropText = System.Text.Json.JsonEncodedText.Encode("text");
	private static readonly System.Text.Json.JsonEncodedText PropTokenizer = System.Text.Json.JsonEncodedText.Encode("tokenizer");

	public override AnalyzeIndexRequest Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
	{
		reader.ValidateToken(System.Text.Json.JsonTokenType.StartObject);
		LocalJsonProperty<string?> propAnalyzer = default;
		LocalJsonProperty<ICollection<string>?> propAttributes = default;
		LocalJsonProperty<ICollection<Elastic.Clients.Elasticsearch.Analysis.ICharFilter>?> propCharFilter = default;
		LocalJsonProperty<bool?> propExplain = default;
		LocalJsonProperty<Elastic.Clients.Elasticsearch.Field?> propField = default;
		LocalJsonProperty<ICollection<Elastic.Clients.Elasticsearch.Analysis.ITokenFilter>?> propFilter = default;
		LocalJsonProperty<string?> propNormalizer = default;
		LocalJsonProperty<ICollection<string>?> propText = default;
		LocalJsonProperty<Elastic.Clients.Elasticsearch.Analysis.ITokenizer?> propTokenizer = default;
		while (reader.Read() && reader.TokenType is System.Text.Json.JsonTokenType.PropertyName)
		{
			if (propAnalyzer.TryRead(ref reader, options, PropAnalyzer))
			{
				continue;
			}

			if (propAttributes.TryRead(ref reader, options, PropAttributes))
			{
				continue;
			}

			if (propCharFilter.TryRead(ref reader, options, PropCharFilter))
			{
				continue;
			}

			if (propExplain.TryRead(ref reader, options, PropExplain))
			{
				continue;
			}

			if (propField.TryRead(ref reader, options, PropField))
			{
				continue;
			}

			if (propFilter.TryRead(ref reader, options, PropFilter))
			{
				continue;
			}

			if (propNormalizer.TryRead(ref reader, options, PropNormalizer))
			{
				continue;
			}

			if (propText.TryRead(ref reader, options, PropText, typeof(SingleOrManyMarker<IReadOnlyCollection<string>?, string>)))
			{
				continue;
			}

			if (propTokenizer.TryRead(ref reader, options, PropTokenizer))
			{
				continue;
			}

			throw new System.Text.Json.JsonException($"Unknown JSON property '{reader.GetString()}' for type '{typeToConvert.Name}'.");
		}

		reader.ValidateToken(System.Text.Json.JsonTokenType.EndObject);
		return new AnalyzeIndexRequest
		{
			Analyzer = propAnalyzer.Value
,
			Attributes = propAttributes.Value
,
			CharFilter = propCharFilter.Value
,
			Explain = propExplain.Value
,
			Field = propField.Value
,
			Filter = propFilter.Value
,
			Normalizer = propNormalizer.Value
,
			Text = propText.Value
,
			Tokenizer = propTokenizer.Value
		};
	}

	public override void Write(System.Text.Json.Utf8JsonWriter writer, AnalyzeIndexRequest value, System.Text.Json.JsonSerializerOptions options)
	{
		writer.WriteStartObject();
		writer.WriteProperty(options, PropAnalyzer, value.Analyzer);
		writer.WriteProperty(options, PropAttributes, value.Attributes);
		writer.WriteProperty(options, PropCharFilter, value.CharFilter);
		writer.WriteProperty(options, PropExplain, value.Explain);
		writer.WriteProperty(options, PropField, value.Field);
		writer.WriteProperty(options, PropFilter, value.Filter);
		writer.WriteProperty(options, PropNormalizer, value.Normalizer);
		writer.WriteProperty(options, PropText, value.Text, typeof(SingleOrManyMarker<IReadOnlyCollection<string>?, string>));
		writer.WriteProperty(options, PropTokenizer, value.Tokenizer);
		writer.WriteEndObject();
	}
}

/// <summary>
/// <para>
/// Get tokens from text analysis.
/// The analyze API performs analysis on a text string and returns the resulting tokens.
/// </para>
/// <para>
/// Generating excessive amount of tokens may cause a node to run out of memory.
/// The <c>index.analyze.max_token_count</c> setting enables you to limit the number of tokens that can be produced.
/// If more than this limit of tokens gets generated, an error occurs.
/// The <c>_analyze</c> endpoint without a specified index will always use <c>10000</c> as its limit.
/// </para>
/// </summary>
[JsonConverter(typeof(AnalyzeIndexRequestConverter))]
public sealed partial class AnalyzeIndexRequest : PlainRequest<AnalyzeIndexRequestParameters>
{
	public AnalyzeIndexRequest()
	{
	}

	public AnalyzeIndexRequest(Elastic.Clients.Elasticsearch.IndexName? index) : base(r => r.Optional("index", index))
	{
	}

	internal override ApiUrls ApiUrls => ApiUrlLookup.IndexManagementAnalyze;

	protected override HttpMethod StaticHttpMethod => HttpMethod.POST;

	internal override bool SupportsBody => true;

	internal override string OperationName => "indices.analyze";

	/// <summary>
	/// <para>
	/// The name of the analyzer that should be applied to the provided <c>text</c>.
	/// This could be a built-in analyzer, or an analyzer that’s been configured in the index.
	/// </para>
	/// </summary>
	public string? Analyzer { get; set; }

	/// <summary>
	/// <para>
	/// Array of token attributes used to filter the output of the <c>explain</c> parameter.
	/// </para>
	/// </summary>
	public ICollection<string>? Attributes { get; set; }

	/// <summary>
	/// <para>
	/// Array of character filters used to preprocess characters before the tokenizer.
	/// </para>
	/// </summary>
	public ICollection<Elastic.Clients.Elasticsearch.Analysis.ICharFilter>? CharFilter { get; set; }

	/// <summary>
	/// <para>
	/// If <c>true</c>, the response includes token attributes and additional details.
	/// </para>
	/// </summary>
	public bool? Explain { get; set; }

	/// <summary>
	/// <para>
	/// Field used to derive the analyzer.
	/// To use this parameter, you must specify an index.
	/// If specified, the <c>analyzer</c> parameter overrides this value.
	/// </para>
	/// </summary>
	public Elastic.Clients.Elasticsearch.Field? Field { get; set; }

	/// <summary>
	/// <para>
	/// Array of token filters used to apply after the tokenizer.
	/// </para>
	/// </summary>
	public ICollection<Elastic.Clients.Elasticsearch.Analysis.ITokenFilter>? Filter { get; set; }

	/// <summary>
	/// <para>
	/// Normalizer to use to convert text into a single token.
	/// </para>
	/// </summary>
	public string? Normalizer { get; set; }

	/// <summary>
	/// <para>
	/// Text to analyze.
	/// If an array of strings is provided, it is analyzed as a multi-value field.
	/// </para>
	/// </summary>
	public ICollection<string>? Text { get; set; }

	/// <summary>
	/// <para>
	/// Tokenizer to use to convert text into tokens.
	/// </para>
	/// </summary>
	public Elastic.Clients.Elasticsearch.Analysis.ITokenizer? Tokenizer { get; set; }
}

/// <summary>
/// <para>
/// Get tokens from text analysis.
/// The analyze API performs analysis on a text string and returns the resulting tokens.
/// </para>
/// <para>
/// Generating excessive amount of tokens may cause a node to run out of memory.
/// The <c>index.analyze.max_token_count</c> setting enables you to limit the number of tokens that can be produced.
/// If more than this limit of tokens gets generated, an error occurs.
/// The <c>_analyze</c> endpoint without a specified index will always use <c>10000</c> as its limit.
/// </para>
/// </summary>
public sealed partial class AnalyzeIndexRequestDescriptor<TDocument> : RequestDescriptor<AnalyzeIndexRequestDescriptor<TDocument>, AnalyzeIndexRequestParameters>
{
	internal AnalyzeIndexRequestDescriptor(Action<AnalyzeIndexRequestDescriptor<TDocument>> configure) => configure.Invoke(this);

	public AnalyzeIndexRequestDescriptor(Elastic.Clients.Elasticsearch.IndexName? index) : base(r => r.Optional("index", index))
	{
	}

	public AnalyzeIndexRequestDescriptor() : this(typeof(TDocument))
	{
	}

	internal override ApiUrls ApiUrls => ApiUrlLookup.IndexManagementAnalyze;

	protected override HttpMethod StaticHttpMethod => HttpMethod.POST;

	internal override bool SupportsBody => true;

	internal override string OperationName => "indices.analyze";

	public AnalyzeIndexRequestDescriptor<TDocument> Index(Elastic.Clients.Elasticsearch.IndexName? index)
	{
		RouteValues.Optional("index", index);
		return Self;
	}

	private string? AnalyzerValue { get; set; }
	private ICollection<string>? AttributesValue { get; set; }
	private ICollection<Elastic.Clients.Elasticsearch.Analysis.ICharFilter>? CharFilterValue { get; set; }
	private bool? ExplainValue { get; set; }
	private Elastic.Clients.Elasticsearch.Field? FieldValue { get; set; }
	private ICollection<Elastic.Clients.Elasticsearch.Analysis.ITokenFilter>? FilterValue { get; set; }
	private string? NormalizerValue { get; set; }
	private ICollection<string>? TextValue { get; set; }
	private Elastic.Clients.Elasticsearch.Analysis.ITokenizer? TokenizerValue { get; set; }

	/// <summary>
	/// <para>
	/// The name of the analyzer that should be applied to the provided <c>text</c>.
	/// This could be a built-in analyzer, or an analyzer that’s been configured in the index.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor<TDocument> Analyzer(string? analyzer)
	{
		AnalyzerValue = analyzer;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Array of token attributes used to filter the output of the <c>explain</c> parameter.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor<TDocument> Attributes(ICollection<string>? attributes)
	{
		AttributesValue = attributes;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Array of character filters used to preprocess characters before the tokenizer.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor<TDocument> CharFilter(ICollection<Elastic.Clients.Elasticsearch.Analysis.ICharFilter>? charFilter)
	{
		CharFilterValue = charFilter;
		return Self;
	}

	/// <summary>
	/// <para>
	/// If <c>true</c>, the response includes token attributes and additional details.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor<TDocument> Explain(bool? explain = true)
	{
		ExplainValue = explain;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Field used to derive the analyzer.
	/// To use this parameter, you must specify an index.
	/// If specified, the <c>analyzer</c> parameter overrides this value.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor<TDocument> Field(Elastic.Clients.Elasticsearch.Field? field)
	{
		FieldValue = field;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Field used to derive the analyzer.
	/// To use this parameter, you must specify an index.
	/// If specified, the <c>analyzer</c> parameter overrides this value.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor<TDocument> Field<TValue>(Expression<Func<TDocument, TValue>> field)
	{
		FieldValue = field;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Field used to derive the analyzer.
	/// To use this parameter, you must specify an index.
	/// If specified, the <c>analyzer</c> parameter overrides this value.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor<TDocument> Field(Expression<Func<TDocument, object>> field)
	{
		FieldValue = field;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Array of token filters used to apply after the tokenizer.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor<TDocument> Filter(ICollection<Elastic.Clients.Elasticsearch.Analysis.ITokenFilter>? filter)
	{
		FilterValue = filter;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Normalizer to use to convert text into a single token.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor<TDocument> Normalizer(string? normalizer)
	{
		NormalizerValue = normalizer;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Text to analyze.
	/// If an array of strings is provided, it is analyzed as a multi-value field.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor<TDocument> Text(ICollection<string>? text)
	{
		TextValue = text;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Tokenizer to use to convert text into tokens.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor<TDocument> Tokenizer(Elastic.Clients.Elasticsearch.Analysis.ITokenizer? tokenizer)
	{
		TokenizerValue = tokenizer;
		return Self;
	}

	protected override void Serialize(Utf8JsonWriter writer, JsonSerializerOptions options, IElasticsearchClientSettings settings)
	{
		writer.WriteStartObject();
		if (!string.IsNullOrEmpty(AnalyzerValue))
		{
			writer.WritePropertyName("analyzer");
			writer.WriteStringValue(AnalyzerValue);
		}

		if (AttributesValue is not null)
		{
			writer.WritePropertyName("attributes");
			JsonSerializer.Serialize(writer, AttributesValue, options);
		}

		if (CharFilterValue is not null)
		{
			writer.WritePropertyName("char_filter");
			JsonSerializer.Serialize(writer, CharFilterValue, options);
		}

		if (ExplainValue.HasValue)
		{
			writer.WritePropertyName("explain");
			writer.WriteBooleanValue(ExplainValue.Value);
		}

		if (FieldValue is not null)
		{
			writer.WritePropertyName("field");
			JsonSerializer.Serialize(writer, FieldValue, options);
		}

		if (FilterValue is not null)
		{
			writer.WritePropertyName("filter");
			JsonSerializer.Serialize(writer, FilterValue, options);
		}

		if (!string.IsNullOrEmpty(NormalizerValue))
		{
			writer.WritePropertyName("normalizer");
			writer.WriteStringValue(NormalizerValue);
		}

		if (TextValue is not null)
		{
			writer.WritePropertyName("text");
			SingleOrManySerializationHelper.Serialize<string>(TextValue, writer, options);
		}

		if (TokenizerValue is not null)
		{
			writer.WritePropertyName("tokenizer");
			JsonSerializer.Serialize(writer, TokenizerValue, options);
		}

		writer.WriteEndObject();
	}
}

/// <summary>
/// <para>
/// Get tokens from text analysis.
/// The analyze API performs analysis on a text string and returns the resulting tokens.
/// </para>
/// <para>
/// Generating excessive amount of tokens may cause a node to run out of memory.
/// The <c>index.analyze.max_token_count</c> setting enables you to limit the number of tokens that can be produced.
/// If more than this limit of tokens gets generated, an error occurs.
/// The <c>_analyze</c> endpoint without a specified index will always use <c>10000</c> as its limit.
/// </para>
/// </summary>
public sealed partial class AnalyzeIndexRequestDescriptor : RequestDescriptor<AnalyzeIndexRequestDescriptor, AnalyzeIndexRequestParameters>
{
	internal AnalyzeIndexRequestDescriptor(Action<AnalyzeIndexRequestDescriptor> configure) => configure.Invoke(this);

	public AnalyzeIndexRequestDescriptor(Elastic.Clients.Elasticsearch.IndexName? index) : base(r => r.Optional("index", index))
	{
	}

	public AnalyzeIndexRequestDescriptor()
	{
	}

	internal override ApiUrls ApiUrls => ApiUrlLookup.IndexManagementAnalyze;

	protected override HttpMethod StaticHttpMethod => HttpMethod.POST;

	internal override bool SupportsBody => true;

	internal override string OperationName => "indices.analyze";

	public AnalyzeIndexRequestDescriptor Index(Elastic.Clients.Elasticsearch.IndexName? index)
	{
		RouteValues.Optional("index", index);
		return Self;
	}

	private string? AnalyzerValue { get; set; }
	private ICollection<string>? AttributesValue { get; set; }
	private ICollection<Elastic.Clients.Elasticsearch.Analysis.ICharFilter>? CharFilterValue { get; set; }
	private bool? ExplainValue { get; set; }
	private Elastic.Clients.Elasticsearch.Field? FieldValue { get; set; }
	private ICollection<Elastic.Clients.Elasticsearch.Analysis.ITokenFilter>? FilterValue { get; set; }
	private string? NormalizerValue { get; set; }
	private ICollection<string>? TextValue { get; set; }
	private Elastic.Clients.Elasticsearch.Analysis.ITokenizer? TokenizerValue { get; set; }

	/// <summary>
	/// <para>
	/// The name of the analyzer that should be applied to the provided <c>text</c>.
	/// This could be a built-in analyzer, or an analyzer that’s been configured in the index.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor Analyzer(string? analyzer)
	{
		AnalyzerValue = analyzer;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Array of token attributes used to filter the output of the <c>explain</c> parameter.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor Attributes(ICollection<string>? attributes)
	{
		AttributesValue = attributes;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Array of character filters used to preprocess characters before the tokenizer.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor CharFilter(ICollection<Elastic.Clients.Elasticsearch.Analysis.ICharFilter>? charFilter)
	{
		CharFilterValue = charFilter;
		return Self;
	}

	/// <summary>
	/// <para>
	/// If <c>true</c>, the response includes token attributes and additional details.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor Explain(bool? explain = true)
	{
		ExplainValue = explain;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Field used to derive the analyzer.
	/// To use this parameter, you must specify an index.
	/// If specified, the <c>analyzer</c> parameter overrides this value.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor Field(Elastic.Clients.Elasticsearch.Field? field)
	{
		FieldValue = field;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Field used to derive the analyzer.
	/// To use this parameter, you must specify an index.
	/// If specified, the <c>analyzer</c> parameter overrides this value.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor Field<TDocument, TValue>(Expression<Func<TDocument, TValue>> field)
	{
		FieldValue = field;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Field used to derive the analyzer.
	/// To use this parameter, you must specify an index.
	/// If specified, the <c>analyzer</c> parameter overrides this value.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor Field<TDocument>(Expression<Func<TDocument, object>> field)
	{
		FieldValue = field;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Array of token filters used to apply after the tokenizer.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor Filter(ICollection<Elastic.Clients.Elasticsearch.Analysis.ITokenFilter>? filter)
	{
		FilterValue = filter;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Normalizer to use to convert text into a single token.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor Normalizer(string? normalizer)
	{
		NormalizerValue = normalizer;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Text to analyze.
	/// If an array of strings is provided, it is analyzed as a multi-value field.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor Text(ICollection<string>? text)
	{
		TextValue = text;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Tokenizer to use to convert text into tokens.
	/// </para>
	/// </summary>
	public AnalyzeIndexRequestDescriptor Tokenizer(Elastic.Clients.Elasticsearch.Analysis.ITokenizer? tokenizer)
	{
		TokenizerValue = tokenizer;
		return Self;
	}

	protected override void Serialize(Utf8JsonWriter writer, JsonSerializerOptions options, IElasticsearchClientSettings settings)
	{
		writer.WriteStartObject();
		if (!string.IsNullOrEmpty(AnalyzerValue))
		{
			writer.WritePropertyName("analyzer");
			writer.WriteStringValue(AnalyzerValue);
		}

		if (AttributesValue is not null)
		{
			writer.WritePropertyName("attributes");
			JsonSerializer.Serialize(writer, AttributesValue, options);
		}

		if (CharFilterValue is not null)
		{
			writer.WritePropertyName("char_filter");
			JsonSerializer.Serialize(writer, CharFilterValue, options);
		}

		if (ExplainValue.HasValue)
		{
			writer.WritePropertyName("explain");
			writer.WriteBooleanValue(ExplainValue.Value);
		}

		if (FieldValue is not null)
		{
			writer.WritePropertyName("field");
			JsonSerializer.Serialize(writer, FieldValue, options);
		}

		if (FilterValue is not null)
		{
			writer.WritePropertyName("filter");
			JsonSerializer.Serialize(writer, FilterValue, options);
		}

		if (!string.IsNullOrEmpty(NormalizerValue))
		{
			writer.WritePropertyName("normalizer");
			writer.WriteStringValue(NormalizerValue);
		}

		if (TextValue is not null)
		{
			writer.WritePropertyName("text");
			SingleOrManySerializationHelper.Serialize<string>(TextValue, writer, options);
		}

		if (TokenizerValue is not null)
		{
			writer.WritePropertyName("tokenizer");
			JsonSerializer.Serialize(writer, TokenizerValue, options);
		}

		writer.WriteEndObject();
	}
}