// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using Elastic.Clients.Elasticsearch.Core;
using Elastic.Clients.Elasticsearch.Next;
using Elastic.Clients.Elasticsearch.Serialization;
using Elastic.Transport;
using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Elastic.Clients.Elasticsearch.SearchApplication;

[JsonConverter(typeof(EventTypeConverter))]
public enum EventType
{
	[EnumMember(Value = "search_click")]
	Searchclick,
	[EnumMember(Value = "search")]
	Search,
	[EnumMember(Value = "page_view")]
	Pageview
}

internal sealed partial class EventTypeConverter : System.Text.Json.Serialization.JsonConverter<EventType>
{
	private static readonly System.Text.Json.JsonEncodedText MemberSearchclick = System.Text.Json.JsonEncodedText.Encode("search_click");
	private static readonly System.Text.Json.JsonEncodedText MemberSearch = System.Text.Json.JsonEncodedText.Encode("search");
	private static readonly System.Text.Json.JsonEncodedText MemberPageview = System.Text.Json.JsonEncodedText.Encode("page_view");

	public override EventType Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
	{
		reader.ValidateToken(System.Text.Json.JsonTokenType.String);
		if (reader.ValueTextEquals(MemberSearchclick))
		{
			return EventType.Searchclick;
		}

		if (reader.ValueTextEquals(MemberSearch))
		{
			return EventType.Search;
		}

		if (reader.ValueTextEquals(MemberPageview))
		{
			return EventType.Pageview;
		}

		throw new System.Text.Json.JsonException($"Unknown value '{reader.GetString()}' for enum '{nameof(EventType)}'.");
	}

	public override void Write(System.Text.Json.Utf8JsonWriter writer, EventType value, System.Text.Json.JsonSerializerOptions options)
	{
		switch (value)
		{
			case EventType.Searchclick:
				writer.WriteStringValue(MemberSearchclick);
				break;
			case EventType.Search:
				writer.WriteStringValue(MemberSearch);
				break;
			case EventType.Pageview:
				writer.WriteStringValue(MemberPageview);
				break;
			default:
				throw new System.Text.Json.JsonException($"Invalid value '{value}' for enum '{nameof(EventType)}'.");
		}
	}
}